### PR TITLE
Update CHANGELOG about 2.0.0 release date

### PR DESCRIPTION
**Pull request by PikachuEXE**

### CODE REVIEW

**Comment by magni-** [comment]
Are there any breaking changes? The changelog doesn't make it clear why there's a major version bump.

**Comment by PikachuEXE** [comment]
I have no idea
I am here only to fix the documented release date :)

**Comment by tisba** [comment]
> Are there any breaking changes? The changelog doesn't make it clear why there's a major version bump.

The drop in supported Rubies alone is a breaking change. The Changelog could be a bit more elaborate on this though :)

**Review by cyu — APPROVED** [review]

**Comment by cyu** [comment]
Thanks!

**Comment by wvengen** [comment]
It looks like support for Ruby 2.2 was dropped (and 2.7 added) in fa6882be0476228800a4c32df9da489ea4f61eb9

**Pull request merged**
