### PR TITLE
specify how to include all files in the subdirectories of a directory

### PR DESCRIPTION
**Pull request by jjb**
document how to include files in subdirectories

https://github.com/cyu/rack-cors/issues/79

### CODE REVIEW

**Comment by jjb** [comment]
@cyu is this correct?

**Comment by quangle** [comment]
@jjb Thank you very much for creating this PR. It helped us figure a CORS issue with assets in subfolders. 👍

**Comment by cyu** [comment]
Merged.  Thanks!

**Comment by jjb** [comment]
🆒

**Pull request merged**
